name: SEMA ENERGY
favicon: null
layout_spectrum: 0.41745990817435086
typography_spectrum: 0.793554101837799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7958072738256305
  lightness: 0.6164523120969534
  saturation: 0.6288830651901662
  rhythmicContrast: 0.7990462596062571
purpose: []
